#Define base image
FROM node:16.17.1-alpine3.16
# # Create a directory
# RUN mkdir /client
#Define Working Directory
WORKDIR /client
#copy package.json and package-lock.json to the working directory
COPY package*.json ./
RUN npm install
# Bundle app source
COPY . .
#Build for production
RUN npm run build
#Static server
RUN npm install -g serve
#Expose port 3000
EXPOSE 3000
#Define an entry point
CMD [ "serve", "-s", "build", "-l", "3000" ]