#Define base image
FROM node:16.17.1-alpine3.16
# # Create a directory
# RUN mkdir /client
#Define Working Directory
WORKDIR /client
#copy package.json and package-lock.json to the working directory
COPY package*.json ./
#install dependencies
RUN npm install
# Copy rest of the app to the working directory
COPY . . /
# Expose port 3000
EXPOSE 3000
#Define an entry point
CMD [ "npm", "start" ]
