#Define base image
FROM mongo-express:latest
# Create a directory
RUN mkdir -p /app
#Define Working Directory
WORKDIR /app
#copy package.json and package-lock.json to the working directory
COPY package*.json /app/
# RUN npm install
RUN npm install
# Bundle app source
COPY . /app/
#Define an entry point
CMD [ "npm","start" ]