---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "yoloappk-service"
  namespace: "default"
  labels:
    app: "yoloappk"
spec:
  ports:
  - protocol: "TCP"
    port: 3000
    targetPort: 3000
  selector:
    app: "yoloappk"
  type: "LoadBalancer"
  loadBalancerIP: ""
