---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "yolo-rodney080-service"
  namespace: "default"
  labels:
    app: "yolo-rodney080"
spec:
  ports:
  - protocol: "TCP"
    port: 3000
    targetPort: 5000
  selector:
    app: "yolo-rodney080"
  type: "LoadBalancer"
  loadBalancerIP: ""
